build:
  image: jdubois/jhipster-docker:latest
  working_dir: /home/jhipster/app
  volumes:
    - /var/jenkins_home/jobs/tracker/workspace:/home/jhipster/app
    - /root/.m2:/home/jhipster/.m2:rw
  command: mvn clean verify -Pprod -Dmaven.test.skip=true
